const sampleData = [
  // Creators
  {
    id: 1,
    userType: 'creator',
    name: 'Tech Review Guy',
    platform: 'youtube',
    followers: 125000,
    interests: ['technology', 'reviews', 'gaming'],
    pricePoint: 800,
    description: 'I create in-depth tech reviews and unboxings for a tech-savvy audience aged 18-35. My community is highly engaged and trusts my recommendations.',
    contactInfo: 'techreviewguy@email.com',
    avatar: '🎬',
    verified: true
  },
  {
    id: 2,
    userType: 'creator',
    name: 'Fitness Journey',
    platform: 'instagram',
    followers: 85000,
    interests: ['fitness', 'wellness', 'lifestyle'],
    pricePoint: 450,
    description: 'Fitness enthusiast sharing workout routines and healthy lifestyle tips. My audience is 70% female, ages 20-40.',
    contactInfo: '@fitnessjourney_official',
    avatar: '💪',
    verified: true
  },
  {
    id: 3,
    userType: 'creator',
    name: 'Gaming Central',
    platform: 'twitch',
    followers: 45000,
    interests: ['gaming', 'streaming', 'esports'],
    pricePoint: 350,
    description: 'Daily gaming streams with focus on FPS and battle royale games. Highly interactive community.',
    contactInfo: 'partnerships@gamingcentral.tv',
    avatar: '🎮',
    verified: false
  },
  {
    id: 4,
    userType: 'creator',
    name: 'Food Adventures',
    platform: 'tiktok',
    followers: 200000,
    interests: ['food', 'cooking', 'recipes'],
    pricePoint: 600,
    description: 'Quick cooking videos and food reviews. Audience loves trying new recipes and food products.',
    contactInfo: 'hello@foodadventures.co',
    avatar: '🍳',
    verified: true
  },
  {
    id: 5,
    userType: 'creator',
    name: 'Style & Beauty',
    platform: 'instagram',
    followers: 95000,
    interests: ['beauty', 'fashion', 'lifestyle'],
    pricePoint: 500,
    description: 'Beauty tutorials and fashion inspiration. Audience is 80% female, ages 16-30.',
    contactInfo: 'collabs@stylebeauty.com',
    avatar: '💄',
    verified: true
  },
  {
    id: 6,
    userType: 'creator',
    name: 'Travel Diaries',
    platform: 'youtube',
    followers: 75000,
    interests: ['travel', 'adventure', 'culture'],
    pricePoint: 650,
    description: 'Travel vlogs and destination guides. Audience loves adventure and discovering new places.',
    contactInfo: 'partnerships@traveldiaries.net',
    avatar: '✈️',
    verified: true
  },
  {
    id: 7,
    userType: 'creator',
    name: 'Art & Design',
    platform: 'instagram',
    followers: 55000,
    interests: ['art', 'design', 'creativity'],
    pricePoint: 300,
    description: 'Digital art tutorials and design inspiration. Community of aspiring artists and designers.',
    contactInfo: 'hello@artanddesign.studio',
    avatar: '🎨',
    verified: false
  },
  {
    id: 8,
    userType: 'creator',
    name: 'Business Tips',
    platform: 'linkedin',
    followers: 40000,
    interests: ['business', 'entrepreneurship', 'finance'],
    pricePoint: 750,
    description: 'Business advice and entrepreneurship content. Audience of professionals and business owners.',
    contactInfo: 'connect@businesstips.pro',
    avatar: '💼',
    verified: true
  },
  {
    id: 9,
    userType: 'creator',
    name: 'Pet Life',
    platform: 'tiktok',
    followers: 180000,
    interests: ['pets', 'animals', 'lifestyle'],
    pricePoint: 400,
    description: 'Cute pet videos and pet care tips. Audience of pet owners and animal lovers.',
    contactInfo: 'petlife.creator@gmail.com',
    avatar: '🐕',
    verified: true
  },
  {
    id: 10,
    userType: 'creator',
    name: 'Home & Garden',
    platform: 'youtube',
    followers: 65000,
    interests: ['home', 'garden', 'diy'],
    pricePoint: 380,
    description: 'Home improvement and gardening content. Audience of homeowners interested in DIY projects.',
    contactInfo: 'homeandgarden@creators.com',
    avatar: '🏡',
    verified: false
  },

  // Sponsors
  {
    id: 11,
    userType: 'sponsor',
    name: 'TechStart Pro',
    platform: 'youtube',
    followers: 50000,
    interests: ['technology', 'software', 'productivity'],
    pricePoint: 900,
    description: 'Productivity software for tech professionals. Looking for tech reviewers and productivity creators.',
    contactInfo: 'marketing@techstartpro.com',
    avatar: '💻',
    verified: true
  },
  {
    id: 12,
    userType: 'sponsor',
    name: 'FitGear Plus',
    platform: 'instagram',
    followers: 25000,
    interests: ['fitness', 'sports', 'health'],
    pricePoint: 500,
    description: 'Premium fitness equipment and accessories. Seeking fitness influencers and athletes.',
    contactInfo: 'partnerships@fitgearplus.com',
    avatar: '🏋️',
    verified: false
  },
  {
    id: 13,
    userType: 'sponsor',
    name: 'Gourmet Foods Co',
    platform: 'tiktok',
    followers: 15000,
    interests: ['food', 'cooking', 'gourmet'],
    pricePoint: 650,
    description: 'Artisanal food products and gourmet ingredients. Perfect for food creators and chefs.',
    contactInfo: 'hello@gourmetfoods.co',
    avatar: '🍯',
    verified: true
  },
  {
    id: 14,
    userType: 'sponsor',
    name: 'Urban Style',
    platform: 'instagram',
    followers: 30000,
    interests: ['fashion', 'streetwear', 'lifestyle'],
    pricePoint: 400,
    description: 'Trendy streetwear brand targeting young adults. Looking for fashion and lifestyle creators.',
    contactInfo: 'collabs@urbanstyle.fashion',
    avatar: '👟',
    verified: true
  },
  {
    id: 15,
    userType: 'sponsor',
    name: 'EcoLife Products',
    platform: 'youtube',
    followers: 20000,
    interests: ['sustainability', 'eco-friendly', 'lifestyle'],
    pricePoint: 550,
    description: 'Sustainable living products. Seeking environmentally conscious creators and lifestyle bloggers.',
    contactInfo: 'partnerships@ecolife.green',
    avatar: '🌱',
    verified: false
  },
  {
    id: 16,
    userType: 'sponsor',
    name: 'GameZone Accessories',
    platform: 'twitch',
    followers: 35000,
    interests: ['gaming', 'accessories', 'tech'],
    pricePoint: 450,
    description: 'Gaming peripherals and accessories. Perfect for gaming streamers and tech reviewers.',
    contactInfo: 'sponsor@gamezone.gg',
    avatar: '🎯',
    verified: true
  },
  {
    id: 17,
    userType: 'sponsor',
    name: 'Beauty Essence',
    platform: 'instagram',
    followers: 18000,
    interests: ['beauty', 'skincare', 'cosmetics'],
    pricePoint: 600,
    description: 'Organic skincare and beauty products. Looking for beauty influencers and lifestyle creators.',
    contactInfo: 'marketing@beautyessence.com',
    avatar: '✨',
    verified: true
  },
  {
    id: 18,
    userType: 'sponsor',
    name: 'Adventure Gear',
    platform: 'youtube',
    followers: 40000,
    interests: ['travel', 'adventure', 'outdoor'],
    pricePoint: 700,
    description: 'Outdoor and adventure equipment. Seeking travel vloggers and adventure creators.',
    contactInfo: 'partnerships@adventuregear.co',
    avatar: '🏔️',
    verified: false
  },
  {
    id: 19,
    userType: 'sponsor',
    name: 'Smart Home Hub',
    platform: 'youtube',
    followers: 22000,
    interests: ['smart home', 'technology', 'automation'],
    pricePoint: 800,
    description: 'Smart home devices and automation systems. Perfect for tech reviewers and home improvement creators.',
    contactInfo: 'hello@smarthomehub.tech',
    avatar: '🏠',
    verified: true
  },
  {
    id: 20,
    userType: 'sponsor',
    name: 'Pet Paradise',
    platform: 'tiktok',
    followers: 28000,
    interests: ['pets', 'pet care', 'animals'],
    pricePoint: 350,
    description: 'Premium pet products and accessories. Looking for pet influencers and animal lovers.',
    contactInfo: 'collabs@petparadise.store',
    avatar: '🐾',
    verified: true
  }
];

module.exports = sampleData;